# loop logistics
epochs: 15
start_epoch: 0
print_freq: 10

# loss
contrast_type: "nearest" # ["nearest", "class_aware"]
ce_type: "reduction_none" # ["standard", "reduction_none"]
use_mixup_ws: True
use_proto_loss_v2: True
alpha: 1.0
beta: 1.0
eta: 1.0
add_gt_in_bank : True

# algo-related stuff
aug_versions: "wss" # ["w", "ws", "wss", "ss"]
val_aug_versions: "o"
dist_type: "cosine" # ["cosine", "euclidean"]
ce_sup_type: "weak_strong" # ["weak_all", "weak_weak", "weak_strong", "conb_strong_strong", "weak_strong_kl"]
refine_method: "nearest_neighbors" #"nearest_feat" #["conf_based_nearest_neighbors", "nearest_feat", "nearest_neighbors"]
num_neighbors: 10
queue_size: -1
epoch_labeling: false

# For Noisy Detector
conf_filter: 0.5
near: 10
do_noise_detect: True
use_ce_weight: True
use_mixup_weight: True

use_projector_q: False
use_classfier_q: False
sep_gmm: False
use_confidence_instance_loss : False
# Fro vislized
return_index : True
